```{r}
library(dplyr)
library(quadprog)
library(sjlabelled)

allGenres = read.csv(file = '~/Documents/dp_datamining/data/allGenresV2.csv', sep = ";", header = TRUE, na.strings = "?")
othersG = read.csv(file = '~/Documents/dp_datamining/data/othersG.csv', sep = ";", header = TRUE, na.strings = "?")

#Remove "tempo equals 0, because is not relevante for now."
allGenres <- allGenres[!allGenres$tempo <= 45.0 & !allGenres$tempo >= 250.0,]
othersG <- othersG[!othersG$tempo <= 45.0 & !othersG$tempo >= 250.0,]
#Remove column from this set
allGenres$titlesong <- NULL
allGenres$typegroup <- NULL
allGenres$duration <- NULL

othersG$titlesong <- NULL
othersG$typegroup <- NULL
othersG$duration <- NULL

allGenres$Class[allGenres$genretype=='Others'] <- 0
allGenres$Class[allGenres$genretype=='Rock'] <- 1
allGenres$Class[allGenres$genretype=='Pop'] <- 2
allGenres$Class[allGenres$genretype=='Hip Hop'] <- 3
allGenres$Class[allGenres$genretype=='Jazz'] <- 4
allGenres$Class[allGenres$genretype=='Funk'] <- 5
allGenres$Class[allGenres$genretype=='Folk'] <- 6
allGenres$Class[allGenres$genretype=='Classical'] <- 7
allGenres$Class[allGenres$genretype=='Blues'] <- 8
allGenres$Class[allGenres$genretype=='Country'] <- 9
allGenres$Class[allGenres$genretype=='Electronic'] <- 10

#othersG <- othersG[ sample( which(othersG$genretype== "Others"), round(0.5*length(which(othersG$genretype== "Others")))), ]

summary(allGenres$genretype)
summary(allGenres)
summary(othersG)
```
```{r}
# # Split between 80 and 30
# index <- sample(1:nrow(allGenres),size = 0.7* nrow(allGenres))
# # Use the large partition to training - 70
# train <- allGenres[index,]
# train <- train[which(!train$genretype=='NA'),]
# summary(train)
# summary(train$genretype)
# # Use the small partition to test - 30
# test <- allGenres[-index,]
# test <- test[which(!test$genretype=='NA'),]
# summary(test)



library("splitstackshape")
test<-stratified(allGenres,"Class", size=.2)
train<-setdiff(allGenres,test)
train <- train[which(!train$genretype=='NA'),]
test <- test[which(!test$genretype=='NA'),]
summary(train)
summary(train$genretype)

summary(test)

```

```{r}
library(rpart)
library(rpart.plot)
#Build the first classfication model
#to using the command rpat, R will build a tree where Class is to be predicted from the variable presents at the formula

#Model classfication of train
#tempo+energy+danceability+speechiness+accoustiness+loudness+loudness+duration+valence+instrumentalness-Class-genretype
set.seed(7)
lvaFormula = Class ~ +tempo+energy+danceability+speechiness+accoustiness+loudness+loudness+valence+instrumentalness-Class-genretype

trainTree = rpart(lvaFormula, data = train, method = "class", cp=0)

#Plotting the tree of train
plotcp(trainTree)
plot(trainTree, compress=TRUE, uniform=TRUE)
text(trainTree,use.n = T,all=T,cex=.7, pretty=0, xpd=TRUE, digits = 6)
prp(trainTree, extra=101)
# Visualize the decision tree with rpart.plot
rpart.plot(trainTree, box.palette="RdBu", shadow.col="gray", nn=TRUE)
#Test errors of train tree
pred <- predict(trainTree, test, type = "class")
mConfusion <- table(test$genretype, pred)
print(mConfusion)

#Test Accuracy of model
acc <- (mConfusion[1,1]+mConfusion[2,2])/sum(mConfusion)
print("acc")
print(acc)

#Compute error rate
Err <- (mConfusion[1,2]+mConfusion[2,1])/sum(mConfusion)
print("err")
print(Err)
```

```{r}
pred <- predict(trainTree, test, type = "class")
  mConfusion <- table(test$Class, pred)
  print(mConfusion)
  # #Test Accuracy of model
  # acc <- (mConfusion[1,1]+mConfusion[2,2])/sum(mConfusion)
  # print("acc")
  # print(acc)
  # 
  # #Compute error rate
  # Err <-(mConfusion[1,2]+mConfusion[2,1])/sum(mConfusion)
  # print("err")
  # print(Err)
  
  Acc <- (mConfusion[1,1]+mConfusion[2,2]+mConfusion[3,3]+mConfusion[4,4]+mConfusion[5,5]+mConfusion[6,6]+mConfusion[7,7]+mConfusion[8,8]+mConfusion[9,9]+mConfusion[10,10])/sum(mConfusion)
  print("Acc")
  print(Acc)
  
  TrainErr <- 1 - Acc
  print("Err")
  print(TrainErr)
  
```

```{r}
pred <- predict(trainTree, othersG, type = "class")
  mConfusion <- table(othersG$genretype, pred)
  print(mConfusion)
  
  # Acc <- (mConfusion[1,1]+mConfusion[2,2])/sum(mConfusion)
  # print("Acc")
  # print(TrainAcc)
  # 
  # TrainErr <- 1 -Acc
  # print("Err")
  # print(TrainErr)
```

