---
title: "R Notebook - Discover of Data set genre"
output: none
---

We want to learn more about our dataset others.

```{r}
#Load data
othersG = read.csv(file = '~/Documents/dp_datamining/data/othersG.csv',sep = ";", header = TRUE, na.strings = "?")
#Remove lyrics from this set
othersG$titlesong <- NULL
#Remove "tempo equals 0, because is not relevante now."
othersG <- othersG[!othersG$tempo <= 45.0 & !othersG$tempo >= 250.0,]

```



```{r}
#check dim()
dim(othersG)
#summary data
summary(othersG)
#name
names(othersG)

# VIM library for using 'aggr'
library(VIM)
# 'aggr' plots the amount of missing/imputed values in each column
aggr(othersG)
```


```{r}
library("splitstackshape")
test<-stratified(othersG,"genretype", size=.5)

train_kms<-setdiff(othersG,test)
train_kms <- train_kms[which(!train_kms$genretype=='NA'),]
summary(train_kms)
summary(train_kms$genretype)

test_kms <- test[which(!test$genretype=='NA'),]
summary(test_kms)


train_kms[,1:3]


```






```{r}
summary(train_kms)
#Remove genretype from this set
train_kms$genretype <- NULL
train_kms$typegroup <- NULL


#Prepare Data Clustering
mydata <- na.omit(train_kms) # listwise deletion of missing
mydata <- scale(mydata) # standardize variables

set.seed(20)
# Determine number of clusters
wss <- (nrow(mydata)-1)*sum(apply(mydata,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(mydata, 
   centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
  ylab="Within groups sum of squares")

set.seed(20)
# K-Means Cluster Analysis
fit <- kmeans(mydata, 5) # 7 cluster solution
# get cluster means 
aggregate(mydata,by=list(fit$cluster),FUN=mean)
# append cluster assignment
mydata <- data.frame(mydata, fit$cluster)

set.seed(20)
# Ward Hierarchical Clustering
d <- dist(mydata, method = "euclidean") # distance matrix
fit <- hclust(d, method="ward") 
plot(fit) # display dendogram
groups <- cutree(fit, k=3) # cut tree into 3 clusters
# draw dendogram with red borders around the 3 clusters 
rect.hclust(fit, k=3, border="red")

set.seed(20)
# Ward Hierarchical Clustering with Bootstrapped p values
library(pvclust)
fit <- pvclust(mydata, method.hclust="ward",
   method.dist="euclidean")
plot(fit) # dendogram with p values
# add rectangles around groups highly supported by the data
pvrect(fit, alpha=.95)

```

# ```{r}
# # Model Based Clustering
# library(mclust)
# fit <- Mclust(mydata)
# plot(fit) # plot results 
# summary(fit) # display the best model
# ```

```{r}
# K-Means Clustering with 5 clusters
fit <- kmeans(mydata[,1:4], 5)

# translate into a two dimensions using multidimensional scaling

## Original 
# plot(mydata,
#      ylim = c(-5,5),
#      xlim = c(-5,5),
#      col = 'green',
#      main = 'Original Data')

palette(c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3",  "#FF7F00", "#FFFF33", "#A65628", "#F781BF", "#999999", "#000000"))
plot(mydata, col=fit$cluster, pch = 20, cex = 3)
points(fit$centers, pch = 8, cex = 2)
# Cluster Plot against 1st 2 principal components
set.seed(20)
# vary parameters for most readable graph
library(cluster) 
clusplot(mydata,
         fit$cluster,
         main = 'Cusplot',
         color=TRUE,
         shade=TRUE,
         labels=5,
         lines=3)
set.seed(20)
# Centroid Plot against 1st 2 discriminant functions
library(fpc)
plotcluster(mydata, fit$cluster)
```






```{r}
#Remove typegroup from this set to test Clustering
df_toCov <- othersG
df_toCov$typegroup <- NULL
df_toCov$genretype <- NULL
summary(df_toCov)
x <- df_toCov
# x est une variable de type matrix ou data.frame
cor(x, method = c("pearson", "kendall", "spearman"))

mcor <- cor(x)

library(corrplot)
#https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html
## corrplot 0.84 loaded
M <- cor(x)
corrplot(M, method = "circle")

```

