```{r}
library(dplyr)
library(quadprog)
library(sjlabelled)


allGenres = read.csv(file = '~/Documents/dp_datamining/data/dataGenre.csv', header = TRUE, na.strings = "?")
othersG = read.csv(file = '~/Documents/dp_datamining/data/othersG.csv', sep = ";", header = TRUE, na.strings = "?")




#Remove "tempo equals 0, because is not relevante for now."
allGenres <- allGenres[!allGenres$tempo <= 45.0 & !allGenres$tempo >= 250.0,]
othersG <- othersG[!othersG$tempo <= 45.0 & !othersG$tempo >= 250.0,]
#Remove column from this set
allGenres$titlesong <- NULL
allGenres$typegroup <- NULL

othersG$titlesong <- NULL
othersG$typegroup <- NULL

othersG <- othersG[ sample( which(othersG$genretype== "Others"), round(0.05*length(which(othersG$genretype== "Others")))), ]

summary(allGenres$genretype)
summary(allGenres)
summary(othersG)

```

```{r}
library(caret)

# Split between 80 and 30
#index_Rock <- sample(1:nrow(rock_df),size = 0.7* nrow(rock_df))
index_allGenre <- createDataPartition(y = allGenres$genretype, p= 0.7, list = FALSE)
# Use the large partition to training - 70
train_allGenre <- allGenres[index_allGenre,]
# Use the small partition to test - 30
test_allGenre <- allGenres[-index_allGenre,]

#train_allGenre <- train_allGenre[which(!train_allGenre$genretype=='NA'),]
str(train_allGenre)
summary(train_allGenre)
str(train_allGenre)
class(train_allGenre)

#test_allGenre <- test_allGenre[which(!test_allGenre$genretype=='NA'),]
str(test_allGenre)
summary(test_allGenre)
str(test_allGenre)
class(test_allGenre)
```

```{r}
library(caret)
library(lattice)
library(ggplot2)
library(caret)
library(klaR)
library(MASS)

# Run algorithms using 10-fold cross validation
control <- trainControl(method="cv", number=10)
metric <- "Accuracy"

#+tempo+energy+danceability+speechiness+accoustiness+loudness+duration+valence+instrumentalness
formula_SVM <- genretype~ .


#SVM Radial 
grid_radial <- expand.grid(sigma = c(0,
 0.05,0.1, 0.25, 0.5, 0.75,0.9),
 C = c(0,0.01, 0.05, 0.1, 0.25, 0.5, 0.75,
 1, 1.5, 2,5))

set.seed(3233)
controlGrid <- trainControl(method="cv", number=10)
svm_Radial_Grid <- train(genretype ~.,
                         data = train_allGenre,
                         method = "svmRadial",
                         trControl=controlGrid,
                         preProcess = c("center", "scale"),
                         tuneGrid = grid_radial,
                         tuneLength = 10)

svm_Radial_Grid
plot(svm_Radial_Grid)
#plot(svm_Radial_Grid, train_Rock2)
```
```{r}
predRadial <- predict(svm_Radial_Grid, newdata = test_allGenre)
#Confusion Matrix and Statistics
confusionMatrix(predRadial, test_allGenre$genretype )

```


