---
title: "R Notebook"
output: html_notebook
---

```{r}
library(dplyr)
library(quadprog)
library(sjlabelled)

#Loar dataset
popG = read.csv(file = '~/Documents/dp_datamining/data/popSongs.csv', sep = ";", header = TRUE, na.strings = "?")
#Remove column that we will not use
popG$artist_id_spotify <- NULL
popG$album_id <- NULL
popG$track_id <- NULL
popG$track_id <- NULL
popG$date_release <- NULL
popG$album_name <- NULL
popG$date_popularity <- NULL
popG$track_name <- NULL
popG$genreOriginal <- NULL
popG$album_name <- NULL
popG$artist_name <- NULL

#take a sample of genres "Others"
#Only 1% from attributes with the label Others
others_df <- popG[ sample( which(popG$genre== "Others"), round(0.02*length(which(popG$genre== "Others")))), ]

pop_G <- popG[which(popG$genre=='pop'),]
#Reattach A small and random data set with Others
pop_G <- bind_rows(others_df,pop_G)



str(pop_G)
class(pop_G)
summary(pop_G)
```

```{r}
library(MASS)
library(lattice)
library(ggplot2)

my_cols <- c("#FC4E07","#00AFBB")  
pairs(pop_G[,2:14], pch = 20,  cex = 0.4,
      col = my_cols[pop_G$genre])
```
```{r}
library("splitstackshape")
test<-stratified(pop_G,"genre", size=.5)

train<-setdiff(pop_G,test)
train <- train[which(!train$genre=='NA'),]
summary(train)
summary(train$genre)

test <- test[which(!test$genre=='NA'),]
summary(test)
```
```{r}
# Load libraries
library(mlbench)
library(caretEnsemble)
library(caret)
library(lattice)
library(ggplot2)
library(klaR)
library(MASS)
library(dplyr)

# Run algorithms using 10-fold cross validation
#control <- trainControl(method="cv", number=10)
#control <- trainControl(method="boot", number=100)
control <- trainControl(method="repeatedcv", number=10, repeats=3, savePredictions=TRUE, classProbs=TRUE)
#control <- trainControl(method="repeatedcv",number=10,repeats=3,savePredictions='final')
#control <- trainControl(method = "LOOCV", number = 5,verbose = FALSE)

#+tempo+energy+danceability+speechiness+accoustiness+loudness+duration+valence+instrumentalness
formula_SVM <- genre~ .
metric <- "Accuracy"
seed <- 7
#SVMgrid <- expand.grid(sigma = c(0.05,0.0456,0.05,0.06,0.07,0.08,1,1.5,2,3,6,9,12), C = c(0.5,0.6,0.7,1,1.5,1.596,1.65,1.89,1.95,2,2.2,2.5,3,3.4,4,5,7,9,12))
SVMgrid <- expand.grid(sigma = c(0.0456), C = c(1.95))
```
```{r}
#SVM Radial Tunned
set.seed(seed)
fit.svmRadial_train <- train(formula_SVM,
                             data = train,
                             method = "svmRadial",
                             gamma= 1,
                             trControl=control,
                             tuneGrid = SVMgrid,
                             preProcess = c("YeoJohnson", "scale"),
                             tuneLength = 10)
fit.svmRadial_train
#plot(fit.svmRadial_train)


```

```{r}
# Example of Stacking algorithms
# create submodels

algorithmList <- c('lda', 'rpart', 'glm', 'knn', 'svmRadial','rf')
set.seed(seed)
models <- caretList(formula_SVM,
                    data=train,
                    trControl=control,
                    methodList=algorithmList)

results <- resamples(models)
summary(results)
dotplot(results)
```

```{r}
# stack using random forest
set.seed(seed)
stack.rf <- caretStack(models,
                       method="rf",
                       metric=metric,
                       gamma=0,
                       preProcess = c("YeoJohnson", "scale"),
                      tuneLength = 5,
                       trControl=control)
print(stack.rf)

```



```{r}
#Boosting approach
# C5.0
set.seed(seed)
fit.c50 <- train(formula_SVM,
                 data=train,
                 method="C5.0",
                 metric=metric,
                 trControl=control,
                 verbose=FALSE)

# Stochastic Gradient Boosting
set.seed(seed)
fit.gbm <- train(formula_SVM, data=train, method="gbm", metric=metric, trControl=control, verbose=FALSE)

# AdaBoost Classification Trees
set.seed(seed)
fit.LogitBoost <- train(formula_SVM, data=train, method="LogitBoost", metric=metric, trControl=control, verbose=FALSE)
#Boosted Logistic Regression
set.seed(seed)
fit.adaboost <- train(formula_SVM, data=train, method="adaboost", metric=metric, trControl=control, verbose=FALSE)

# summarize results
boosting_results <- resamples(list(c5.0=fit.c50,
                                   gbm=fit.gbm,
                                   LogitBoost=fit.LogitBoost,
                                   adaboost=fit.adaboost,
                                   svmRadial=fit.svmRadial_train))
summary(boosting_results)
dotplot(boosting_results)
```


```{r}
# Bagged CART
set.seed(seed)
fit.treebag <- train(formula_SVM, data=train,gamma=1, method="treebag", metric=metric, trControl=control)
# Random Forest
set.seed(seed)
fit.rf <- train(formula_SVM, data=train,gamma=1, method="rf", metric=metric, trControl=control)


# summarize results
bagging_results <- resamples(list(treebag=fit.treebag,
                                  rf=fit.rf,
                                  svmRadial=fit.svmRadial_train))
summary(bagging_results)
dotplot(bagging_results)
```

```{r}
# compare accuracy of models
#dotplot(results)
plot(fit.svmRadial_train,
     plotType = "line",
     metric = "Accuracy")
```


```{r}
# estimate variable importance
importance <- varImp(fit.svmRadial_train, scale=FALSE)
# summarize importance
print(importance)
# plot importance
plot(importance)
```

```{r}
library(MASS)
library(plot3D)
#Choose the best model
bestModel <- fit.svmRadial_train
test_pred1 <- predict(bestModel, newdata = test) 
confusionMatrix(test_pred1, test$genre)

test_pred2 <- predict(stack.rf, newdata = test)
confusionMatrix(test_pred2, test$genre)

test_pred3 <- predict(fit.gbm, newdata = test)
confusionMatrix(test_pred3, test$genre)

test_pred4 <- predict(fit.rf, newdata = test)
confusionMatrix(test_pred4, test$genre)


```



```{r}

pop_G$genre <- NULL
x <- pop_G
summary(x)
# x est une variable de type matrix ou data.frame
cor(x, method = c("pearson", "kendall", "spearman"))

mcor <- cor(x)

library(corrplot)
#https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html
## corrplot 0.84 loaded
M <- cor(x)
corrplot(M, method = "circle")
```

